baseurl = "http://teste.tag.vc/noticias/"
paginate = 6
summaryLength = 7
DefaultContentLanguage = "pt"

title = "Notícias"

[params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = "02/01/2006"
